In [1]:
from copy import deepcopy
import numpy as np
import pandas as pd

In [3]:
X = np.loadtxt('xclara.txt')

In [4]:
def dist(a, b, ax=1):
    return np.linalg.norm(a - b, axis=ax)

In [8]:
print("Dimension of data points: ",X.shape)

Dimension of data points:  (3000, 2)


In [11]:
k = int(input('No. of clusters: '))

No. of clusters: 3


In [12]:
# X coordinates of random centroids
C_x = np.random.randint(0, np.max(X)-20, size=k)
# Y coordinates of random centroids
C_y = np.random.randint(0, np.max(X)-20, size=k)
C = np.array(list(zip(C_x, C_y)), dtype=np.float32)
print("Initial Centroids")
print(C)

Initial Centroids
[[59. 47.]
 [79. 48.]
 [45. 73.]]


In [13]:
# To store the value of centroids when it updates
C_old = np.zeros(C.shape)

In [14]:
# Cluster Lables(0, 1, 2)
clusters = np.zeros(len(X))

In [15]:
error = dist(C, C_old, None)

In [16]:
# Loop will run till the error becomes zero
while error != 0:
    # Assigning each value to its closest cluster
    for i in range(len(X)):
        distances = dist(X[i], C)
        cluster = np.argmin(distances)
        clusters[i] = cluster
    # Storing the old centroid values
    C_old = deepcopy(C)
    # Finding the new centroids by taking the average value
    for i in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j] == i]
        C[i] = np.mean(points, axis=0)
    error = dist(C, C_old, None)

In [17]:
clusters

array([0., 0., 0., ..., 1., 1., 1.])

In [18]:
C

array([[  9.478045,  10.686052],
       [ 69.92419 , -10.119641],
       [ 40.683628,  59.715893]], dtype=float32)

In [22]:
np.savetxt('cluster.txt', C)